# Generated by Django 2.0.5 on 2018-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestrepensum',
            name='periodo',
            field=models.CharField(choices=[('SD', 'Septiembre - Diciembre'), ('EM', 'Enero - Marzo'), ('AJ', 'Abril - Julio'), ('JA', 'Verano(Julio - Agosto)')], default='SD', max_length=2),
        ),
    ]
