# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrerausb',
            options={'verbose_name': 'carrera', 'verbose_name_plural': 'carreras'},
        ),
        migrations.AlterModelOptions(
            name='materiabase',
            options={'verbose_name': 'materia base', 'verbose_name_plural': 'materias bases'},
        ),
        migrations.AlterModelOptions(
            name='materiaplaneada',
            options={'verbose_name': 'materia creada', 'verbose_name_plural': 'materias creadas'},
        ),
        migrations.AlterModelOptions(
            name='mivotiuser',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='plancreado',
            options={'verbose_name': 'Plan de estudio creado', 'verbose_name_plural': 'Planes de estudio creados'},
        ),
        migrations.AlterModelOptions(
            name='planestudiobase',
            options={'verbose_name': 'plan de estudio base', 'verbose_name_plural': 'planes de estudio bases'},
        ),
        migrations.AlterModelOptions(
            name='trimestreplaneado',
            options={'verbose_name': 'trimestre creado', 'verbose_name_plural': 'trimestres creados'},
        ),
        migrations.AlterUniqueTogether(
            name='carrerausb',
            unique_together=set([('nombre', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='materiaplaneada',
            unique_together=set([('trimestre_cursada_fk', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='plancreado',
            unique_together=set([('nombre', 'usuario_creador_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='planestudiobase',
            unique_together=set([('carrera_fk', 'tipo')]),
        ),
    ]
