# Generated by Django 2.1.1 on 2018-09-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiabase',
            name='creditos',
            field=models.IntegerField(null=True),
        ),
    ]
