# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mivotiuser',
            name='forma_acceso',
        ),
        migrations.RemoveField(
            model_name='mivotiuser',
            name='tipo',
        ),
    ]
