# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0002_auto_20170310_0555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materiaplaneada',
            unique_together=set([]),
        ),
    ]
