# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0002_auto_20170323_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mivotiuser',
            name='estan_cargados_datos_ldap',
        ),
    ]
