# Generated by Django 2.0.5 on 2018-05-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0002_auto_20180501_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='mivotiuser',
            name='estan_cargados_datos_ldap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='forma_acceso',
            field=models.CharField(choices=[('PA', 'CAS'), ('IN', 'Log interno')], default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mivotiuser',
            name='gdrive_id_json_plan',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
