# Generated by Django 2.1.1 on 2018-09-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0002_auto_20180923_1711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relacionmateriacarrera',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='relacionmateriacarrera',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='relacionmateriacarrera',
            name='materia',
        ),
        migrations.AddField(
            model_name='relacionmateriapensumbase',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_misvoti.CarreraUsb'),
        ),
        migrations.DeleteModel(
            name='RelacionMateriaCarrera',
        ),
    ]
