# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0003_remove_mivotiuser_estan_cargados_datos_ldap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mivotiuser',
            name='gdrive_id_json_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
