# Generated by Django 2.0.5 on 2018-05-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0003_auto_20180511_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mivotiuser',
            old_name='carnet',
            new_name='usbid',
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_misvoti.CarreraUsb'),
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='password_cass',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
