# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0003_auto_20170310_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaplaneada',
            name='trimestre_cursada_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_planeadas', to='api_misvoti.TrimestrePlaneado'),
        ),
        migrations.AlterField(
            model_name='mivotiuser',
            name='carnet',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plancreado',
            name='usuario_creador_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trimestreplaneado',
            name='planestudio_pert_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres_planeados', to='api_misvoti.PlanCreado'),
        ),
    ]
