# Generated by Django 2.0.5 on 2018-05-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0004_auto_20180512_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mivotiuser',
            name='carrera',
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='codigo_carrera',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
