# Generated by Django 2.0.5 on 2018-05-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0005_auto_20180512_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mivotiuser',
            old_name='password_cass',
            new_name='password_cas',
        ),
    ]
