# Generated by Django 2.0.5 on 2018-05-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0006_auto_20180512_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='mivotiuser',
            name='anyo_inicio',
            field=models.CharField(default=2018, max_length=4),
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='tipo_pensum',
            field=models.CharField(choices=[('PA', 'Pasantia Larga'), ('PG', 'Proyecto de grado a dedicación exclusiva'), ('ND', 'No definido')], default='PG', max_length=2),
        ),
    ]
