# Generated by Django 2.0.5 on 2018-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_misvoti', '0007_auto_20180512_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mivotiuser',
            name='codigo_carrera',
            field=models.CharField(blank=True, default='0800', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mivotiuser',
            name='tipo_pensum',
            field=models.CharField(choices=[('PA', 'Pasantia Larga'), ('PG', 'Proyecto de grado a dedicación exclusiva'), ('ND', 'No definido')], default='PA', max_length=2),
        ),
    ]
