# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiVotiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarreraUsb',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Correquisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoUSB',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaBase',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('creditos', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('departamento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.DepartamentoUSB')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPlaneada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('esta_retirada', models.BooleanField(default=False)),
                ('materia_base_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.MateriaBase')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('usuario_creador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudioBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anyo', models.CharField(max_length=5)),
                ('tipo', models.CharField(choices=[('PA', 'Pasantia'), ('PG', 'Proyecto de grado a dedicaci\xf3n exclusiva'), ('ND', 'No definido')], default='ND', max_length=2)),
                ('carrera_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.CarreraUsb')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_a_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_mat_a', to='planeador.MateriaBase')),
                ('materia_b_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_mat_b', to='planeador.MateriaBase')),
                ('plan_estudio_base_pert_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.PlanEstudioBase')),
            ],
        ),
        migrations.CreateModel(
            name='TrimestreBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('SD', 'Septiembre - Diciembre'), ('EM', 'Enero - Marzo'), ('AJ', 'Abril - Julio'), ('JA', 'Julio - Agosto')], default='SD', max_length=2)),
                ('anyo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TrimestrePlaneado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planestudio_pert_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.PlanEstudio')),
                ('trimestre_base_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.TrimestreBase')),
            ],
        ),
        migrations.AddField(
            model_name='materiaplaneada',
            name='trimestre_cursada_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.TrimestrePlaneado'),
        ),
        migrations.AddField(
            model_name='correquisito',
            name='materia_a_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corr_mat_a', to='planeador.MateriaBase'),
        ),
        migrations.AddField(
            model_name='correquisito',
            name='materia_b_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corr_mat_b', to='planeador.MateriaBase'),
        ),
        migrations.AddField(
            model_name='correquisito',
            name='plan_estudio_base_pert_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.PlanEstudioBase'),
        ),
    ]
