# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planestudio',
            name='plan_estudio_base_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planeador.PlanEstudioBase'),
            preserve_default=False,
        ),
    ]
