# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0002_planestudio_plan_estudio_base_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentousb',
            name='codigo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
