# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0003_materiaplaneada_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mivotiuser',
            name='carnet',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='cedula',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='estan_cargados_datos_ldap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mivotiuser',
            name='tipo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
