# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0003_auto_20170226_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPlanBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_base_cursar_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.MateriaBase')),
                ('plan_base_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.PlanEstudioBase')),
            ],
        ),
        migrations.RemoveField(
            model_name='trimestrebase',
            name='anyo',
        ),
        migrations.AddField(
            model_name='trimestreplaneado',
            name='anyo',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaplanbase',
            name='trimestre_cursar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeador.TrimestreBase'),
        ),
    ]
