# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0004_auto_20170302_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='mivotiuser',
            name='forma_acceso',
            field=models.CharField(choices=[('PA', 'CAS'), ('IN', 'Log interno')], default='IN', max_length=2),
        ),
    ]
