# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0004_auto_20170226_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planestudiobase',
            name='anyo',
        ),
    ]
