# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0005_remove_planestudiobase_anyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestrebase',
            name='periodo',
            field=models.CharField(choices=[('SD', 'Septiembre - Diciembre'), ('EM', 'Enero - Marzo'), ('AJ', 'Abril - Julio'), ('JA', 'Intensivo(Julio - Agosto)')], default='SD', max_length=2),
        ),
    ]
