# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0006_auto_20170227_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correquisito',
            name='materia_a_fk',
        ),
        migrations.RemoveField(
            model_name='correquisito',
            name='materia_b_fk',
        ),
        migrations.RemoveField(
            model_name='correquisito',
            name='plan_estudio_base_pert_fk',
        ),
        migrations.RemoveField(
            model_name='materiaplanbase',
            name='materia_base_cursar_fk',
        ),
        migrations.RemoveField(
            model_name='materiaplanbase',
            name='plan_base_fk',
        ),
        migrations.RemoveField(
            model_name='materiaplanbase',
            name='trimestre_cursar',
        ),
        migrations.RemoveField(
            model_name='prerequisito',
            name='materia_a_fk',
        ),
        migrations.RemoveField(
            model_name='prerequisito',
            name='materia_b_fk',
        ),
        migrations.RemoveField(
            model_name='prerequisito',
            name='plan_estudio_base_pert_fk',
        ),
        migrations.RemoveField(
            model_name='materiabase',
            name='departamento_fk',
        ),
        migrations.RemoveField(
            model_name='trimestreplaneado',
            name='trimestre_base_fk',
        ),
        migrations.AddField(
            model_name='trimestreplaneado',
            name='periodo',
            field=models.CharField(choices=[('SD', 'Septiembre - Diciembre'), ('EM', 'Enero - Marzo'), ('AJ', 'Abril - Julio'), ('JA', 'Intensivo(Julio - Agosto)')], default='SD', max_length=2),
        ),
        migrations.AlterField(
            model_name='materiabase',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Correquisito',
        ),
        migrations.DeleteModel(
            name='DepartamentoUSB',
        ),
        migrations.DeleteModel(
            name='MateriaPlanBase',
        ),
        migrations.DeleteModel(
            name='Prerequisito',
        ),
        migrations.DeleteModel(
            name='TrimestreBase',
        ),
    ]
