# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeador', '0007_auto_20170227_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaplaneada',
            name='id',
        ),
        migrations.RemoveField(
            model_name='materiaplaneada',
            name='materia_base_fk',
        ),
        migrations.AddField(
            model_name='materiaplaneada',
            name='codigo',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaplaneada',
            name='creditos',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='materiaplaneada',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
